#!/bin/bash

cd

ln -s .zsh/zshenv .zshenv
ln -s .zsh/zprofile .zprofile
ln -s .zsh/zshrc .zshrc
ln -s .zsh/zlogin .zlogin
ln -s .zsh/zlogout .zlogout

read -q '?Backup and Replace bash scripts with zsh ones? [y/N] '; echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    [[ -f .bash_profile && ! -L .bash_profile ]] && mv .bash_profile .bash_profile.bak
    [[ -f .bashrc && ! -L .bashrc ]] && mv .bashrc .bashrc.bak
    [[ -f .profile && ! -L .profile ]] && mv .profile .profile.bak
    [[ -f .bash_login && ! -L .bash_login ]] && mv .bash_login .bash_login.bak
    [[ -f .bash_logout && ! -L .bash_logout ]] && mv .bash_logout .bash_logout.bak
fi

ln -s .zprofile .bash_profile
ln -s .zshrc .bashrc
ln -s .zprofile .profile
ln -s .zlogin .bash_login
ln -s .zlogout .bash_logout

if [ ! -d .zsh ]; then
    read -q '?Do you want to clone zsh from github? [y/N] '; echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git clone https://github.com/htanwar922/.zsh.git
    else
	echo -n 'Path to .zsh directory: '; read zsh_path
	ln -s $zsh_path .zsh
	unset zsh_path
    fi
fi

chsh -s /bin/zsh

